"""Build a simple PDF report for the Bluestock MF project.

Generates `Final_Report.pdf` in the same folder. The script is lightweight: it
lists key files and embeds up to 4 PNG images found in `mf_analysis/notebooks` or
`mf_analysis/dashboard/eda` if present.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
import os

OUT = "Final_Report.pdf"

def find_images(base):
    imgs = []
    for root, dirs, files in os.walk(base):
        for f in files:
            if f.lower().endswith(('.png', '.jpg', '.jpeg')):
                imgs.append(os.path.join(root, f))
    return imgs

def build():
    doc = SimpleDocTemplate(OUT, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph("Bluestock MF — Final Report", styles['Title']))
    story.append(Spacer(1,12))
    readme = "README.md"
    if os.path.exists(readme):
        story.append(Paragraph("Project README:", styles['Heading2']))
        with open(readme, 'r', encoding='utf-8', errors='ignore') as fh:
            txt = fh.read(1000)
        story.append(Paragraph(txt.replace('\n','<br/>'), styles['Normal']))
        story.append(Spacer(1,12))

    story.append(Paragraph("Included visualizations:", styles['Heading2']))
    imgs = find_images('notebooks') + find_images('dashboard') + find_images('.')
    imgs = imgs[:4]
    for im in imgs:
        try:
            story.append(Image(im, width=400, height=200))
            story.append(Spacer(1,12))
        except Exception:
            pass

    story.append(Paragraph("Generated by build_report.py", styles['Normal']))
    doc.build(story)
    print("Wrote", OUT)

if __name__ == '__main__':
    build()
