"""Build a simple PowerPoint presentation for the Bluestock MF project.

Generates `Bluestock_MF_Presentation.pptx` with a title slide and up to 11
content slides embedding images found in `mf_analysis/dashboard/eda`.
"""
from pptx import Presentation
from pptx.util import Inches
import os

OUT = "Bluestock_MF_Presentation.pptx"

def find_images(base):
    imgs = []
    for root, dirs, files in os.walk(base):
        for f in files:
            if f.lower().endswith(('.png', '.jpg', '.jpeg')):
                imgs.append(os.path.join(root, f))
    return imgs

def build():
    prs = Presentation()
    blank_layout = prs.slide_layouts[6]
    title_layout = prs.slide_layouts[0]

    # Title
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = "Bluestock MF — Presentation"
    slide.placeholders[1].text = "12-slide summary generated by build_presentation.py"

    imgs = find_images('dashboard') + find_images('notebooks')
    imgs = imgs[:11]
    for i, im in enumerate(imgs, start=1):
        slide = prs.slides.add_slide(blank_layout)
        left = Inches(0.5)
        top = Inches(0.5)
        try:
            slide.shapes.add_picture(im, left, top, width=Inches(9))
        except Exception:
            pass

    prs.save(OUT)
    print("Wrote", OUT)

if __name__ == '__main__':
    build()
